Replaced .length > 0 with .!empty?
sendgrid/smtpapi-ruby pull request #46
Opened 2017-10-29 19:23 UTC by nvzard

# Fixes https://github.com/sendgrid/smtpapi-ruby/issues/32

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

2017-10-29 19:23 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=46) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=46) it.</sub>

2017-10-29 19:23 UTC, SendGridDX commented
[![CLA assistant check](https://cla.sendgrid.com/pull/badge/not_signed)](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=46) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-ruby?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-ruby?pullRequest=46) it.</sub>

2017-10-30 03:19 UTC, nvzard commented
@thinkingserious please review.

2017-11-21 17:23 UTC, mbernier requested changes

2017-11-21 17:23 UTC, mbernier commented on lib/smtpapi.rb
> -      data['to'] = @to if @to.length > 0
It looks like the Travis build is having some issues with the .emtpy? calls here: https://travis-ci.org/sendgrid/smtpapi-ruby/builds/294550416#L652

Can you please look into this and see what's causing these errors?

2017-12-11 23:09 UTC, mbernier approved these changes

2017-12-11 23:09 UTC, merged

2017-12-11 23:09 UTC, thinkingserious commented
Hello @nvzard,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX